int processa_argumentos(int argc, char* argv[]);
void jogo();
void inicializa_jogo();
void termina_jogo();
void processa_entradas_do_usuario();
void atualiza_mundo_do_jogo();
void renderiza_mundo_do_jogo();
int get_quantidade_jogadores();
void cria_jogadores(int quantidade);
int ler_quantidade_de_jogadores();
int main(int argc, char* argv[]);
